# Generated by Django 5.0.6 on 2024-06-07 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('phone_num', models.CharField(max_length=20, null=True)),
                ('date_inserted', models.DateField(default=datetime.date.today)),
                ('user_name', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
