# Generated by Django 5.0.6 on 2024-06-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
